### <b> Importing Libraries </b>

In [298]:
%reset

In [299]:
import pickle
from torch_geometric.data import DataLoader
import torch_geometric
import torch.nn as nn
import torch
import random

### <b>Graph Datasets</b>

In [300]:
graphs=pickle.load(open("data/graphs.pkl","rb"))

In [301]:
number_range = 671 # 0 to 671 inclusive
set_size = 67

val_class_0 = set(random.sample(range(number_range), set_size))
test_class_0 = set(random.sample(set(range(number_range)) - set(val_class_0), set_size))

val_class_1 = set(random.sample(range(672,len(graphs)), set_size))
test_class_1 = set(random.sample(set(range(672,len(graphs))) - set(val_class_1), set_size))


result_pipe = val_class_0 | val_class_1 | test_class_0 | test_class_1
train_set=set(range(len(graphs)))-result_pipe

len(val_class_0),len(val_class_1),len(test_class_0),len(test_class_1),len(train_set)

C:\Users\rbw19\AppData\Local\Temp\ipykernel_30184\3907160027.py:5: DeprecationWarning: Sampling from a set deprecated
since Python 3.9 and will be removed in a subsequent version.
  test_class_0 = set(random.sample(set(range(number_range)) - set(val_class_0), set_size))
C:\Users\rbw19\AppData\Local\Temp\ipykernel_30184\3907160027.py:8: DeprecationWarning: Sampling from a set deprecated
since Python 3.9 and will be removed in a subsequent version.
  test_class_1 = set(random.sample(set(range(672,len(graphs))) - set(val_class_1), set_size))


(67, 67, 67, 67, 1078)

In [302]:
validation=val_class_0.union(val_class_1)
test=test_class_0.union(test_class_1)
set.intersection(validation,test,train_set)

set()

If there is no intersection then there is no intersection between train,test and validatio

In [303]:
val_data=[graphs[i] for i in val_class_0]+[graphs[i] for i in val_class_1]
test_data=[graphs[i] for i in test_class_0]+[graphs[i] for i in test_class_1]
train_data=[graphs[i] for i in train_set]

In [320]:
train_dataset = DataLoader(train_data, batch_size=4, shuffle=True) # splitting with the batch size of 2
val_dataset= DataLoader(val_data, shuffle=True) 
test_dataset=DataLoader(test_data, shuffle=True)

c:\Users\rbw19\OneDrive\Desktop\GNN_guide\graph_venv\lib\site-packages\torch_geometric\deprecation.py:22: UserWarning: 'data.DataLoader' is deprecated, use 'loader.DataLoader' instead
  warnings.warn(out)


### <b> Model creation and trainning</b>

In [322]:
import torch
import torch.nn as nn
import torch_geometric
from torch_geometric.data import DataLoader

# Assuming you have 'dataset' and 'val_data' DataLoader objects defined

# Define a simple Graph Neural Network (GNN) model
class GNNModel(nn.Module):
    def __init__(self):
        super(GNNModel, self).__init__()
        self.conv1 = torch_geometric.nn.GCNConv(15, 8)
        self.conv2 = torch_geometric.nn.GCNConv(8, 3)
        self.conv3 = torch_geometric.nn.GCNConv(3, 1)
        self.fc = nn.Linear(3, 1) 

    def forward(self, batch_data):
        x, edge_index = batch_data.x, batch_data.edge_index
        x = self.conv1(x, edge_index)
        x = torch.relu(x)
        x = self.conv2(x, edge_index)
        x = torch.relu(x)
        # x = self.conv3(x, edge_index)
        x = self.fc(x)
        x = torch.sigmoid(x)
        return x

model = GNNModel()
criterion = torch.nn.BCEWithLogitsLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.0001)

# Training loop

num_epochs = 10
for epoch in range(num_epochs):
    model.train()
    for batch in train_dataset:
        target = batch.y
        optimizer.zero_grad()
        output = model(batch)

        predictions = torch.round(torch.sigmoid(output))
    
        loss = criterion(predictions.squeeze(), target.float())
        loss.backward()
        optimizer.step()

    # Validation loop
    model.eval()
    correct = 0
    total = 0

    with torch.no_grad():
        for val_batch in val_data:
            val_output = model(val_batch)
            val_predictions = torch.round(torch.sigmoid(val_output))
            labels = val_batch.y.view(-1, 1)
            tensor =(val_predictions == labels)
            # count_true = tensor.sum().item()
            
            correct += (val_predictions == labels).sum().item() #count how many correct predictions are there
            total += labels.size(0)

    print(correct,total)
    val_accuracy = correct / total
    print(f'Epoch {epoch + 1}/{num_epochs}, Loss: {loss.item()}, Validation Accuracy: {val_accuracy}')


947 1310
Epoch 1/10, Loss: 0.6931471824645996, Validation Accuracy: 0.7229007633587786
947 1310
Epoch 2/10, Loss: 0.6931471824645996, Validation Accuracy: 0.7229007633587786
947 1310
Epoch 3/10, Loss: 0.6931471824645996, Validation Accuracy: 0.7229007633587786
947 1310
Epoch 4/10, Loss: 0.6931471824645996, Validation Accuracy: 0.7229007633587786
947 1310
Epoch 5/10, Loss: 0.6931471824645996, Validation Accuracy: 0.7229007633587786
947 1310
Epoch 6/10, Loss: 0.6931471824645996, Validation Accuracy: 0.7229007633587786
947 1310
Epoch 7/10, Loss: 0.6931471824645996, Validation Accuracy: 0.7229007633587786
947 1310
Epoch 8/10, Loss: 0.6931471824645996, Validation Accuracy: 0.7229007633587786
947 1310
Epoch 9/10, Loss: 0.6931471824645996, Validation Accuracy: 0.7229007633587786
947 1310
Epoch 10/10, Loss: 0.6931471824645996, Validation Accuracy: 0.7229007633587786


### <b> Testing and Accuracy measurements <b>

In [330]:
correct = 0
total = 0
tp = 0  # True Positive
tn = 0  # True Negative
fp = 0  # False Positive
fn = 0  # False Negative

with torch.no_grad():
    for val_batch_batch in test_dataset:
        val_output = model(val_batch)
        val_predictions = torch.round(torch.sigmoid(val_output))
        print(val_predictions)
        labels = val_batch.y.view(-1, 1)
        tensor =(val_predictions == labels)
        
        # count_true = tensor.sum().item()
        # Count true positive, true negative, false positive, and false negative
        # print((val_predictions == 1) & (labels == 1))
        # print(val_predictions)
        tp += ((val_predictions == True) & (labels == True)).sum().item()
        
        tn += ((val_predictions == False) & (labels == False)).sum().item()
        fp += ((val_predictions == True) & (labels == False)).sum().item()
        fn += ((val_predictions == False) & (labels == True)).sum().item()
        
        correct += (val_predictions == labels).sum().item() #count how many correct predictions are there
        total += labels.size(0)
        # break

# Calculate precision, recall, and accuracy
print(tp,tn,fp,fn)
precision = tp / (tp + fp) if (tp + fp) > 0 else 0
recall = tp / (tp + fn) if (tp + fn) > 0 else 0
print(correct,total)
accuracy = correct / total


print(f"Accuracy: {accuracy:.4f}")
print(f"Precision: {precision:.4f}")
print(f"Recall: {recall:.4f}")

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]])
tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]])
tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]])
tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]])
tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]])
tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]])
tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.]])
tensor([[0.],

* Model gets overfitted to the class 0 since it is dominating in all the graphs<br>
* need to select the developers who has diversed connections by making a graph with more number of nodes<br>
* can go with some optimizers<br>